version: "2.1"

services:
  
  # (Optional)It's not required if you only want to use Restful API but it's required if you want to use Email Protocol
  frontend:
    # if you want to try our beta version, please refer to https://hub.docker.com/r/sygna/sygna-hub-console/tags
    # to get latest beta version tag, ex: sygna/sygna-hub-console:1.0.2-beta.1
    image: sygna/sygna-hub-console:latest
  #   restart: unless-stopped
  #   depends_on:
  #     - backend
  #   environment:
  #     # replace with your backend url
  #     - BACKEND_API_URL=http://localhost:8080/v1
  #     # (Optional) required only if you want to enable Google login
  #     # its value should match google_login/id entry in config.yml file used by backend
  #     # please add it with your valid GOOGLE_SSO_CLIENT_ID. eg. GOOGLE_SSO_CLIENT_ID=<ID>

  backend:
    # if you want to try our beta version, please refer to https://hub.docker.com/r/sygna/sygna-hub/tags
    # to get latest beta version tag, ex: sygna/sygna-hub:1.0.2-beta.1
    image: sygna/sygna-hub:latest
    # restart: unless-stopped
    # ports:
    #   - 8080:8080
    # volumes:
    #   # replace your path to save log
    #   - "./log:/var/log"
    #   # point this path to your configuration file
    #   - "./config.yml:/app/config.yml:ro"
  # # (Optional) Add this service if you want to use TRISA
  # trisa:
  #   # if you want to try our beta version, please refer to https://hub.docker.com/r/sygna/sygna-hub/tags
  #   # to get latest beta version tag, ex: sygna/sygna-hub-trisa-gateway:1.0.2-beta.1
  #   image: sygna/sygna-hub-trisa-gateway:latest
  #   ports:
  #     - 443:443
  #   depends_on:
  #     - backend
  #   volumes:
  #     # replace your path to save log
  #     - ./log:/var/log
  #     - "./config.yml:/app/config.yml:ro"

  # # (Optional) Add this service if you want to use Veriscope on Shyft
  # # Please read README to lean how to setup shyft relay node
  # shyft-relay:
  #   image: nethermind/nethermind
  #   command: -c /opt/nm/shyft-relay.cfg
  #   volumes:
  #     - ./shyft-relay.cfg:/opt/nm/shyft-relay.cfg
  #     - ./shyftchainspec.json:/opt/nm/shyftchainspec.json
  #     - ./static-nodes.json:/opt/nm/static-nodes.json
  #     - ./shyft-db:/opt/nm/db
